-- This list is used for the order in which blocks appear in the creative menu.
-- Blocks not in this list will not appear. Useful for hiding internal blocks etc.

blockList = {
"Grass",
"Dirt",
"Stone",
"Cobblestone",
"Cobblestone Slab",
"Cobblestone Stairs",
"Mossy Cobblestone",
"Oak Log",
"Oak Leaves",
"Oak Planks",
"Oak Plank Slab",
"Oak Plank Stairs",
"Oak Door",
"Oak Trapdoor",
"Oak Fence",
"Oak Fence Gate",
"TNT",
"Crafting Table",
"Smithing Table",
"Furnace",
"Torch",
"Bricks",
"Sand",
"Sandstone",
"Cut Sandstone",
"Chiseled Sandstone",
"Smooth Sandstone",
"Smooth Stone",
"Smooth Stone Slab",
"Stone Bricks",
"Stone Brick Stairs",
"Stone Brick Slab",
"Soul Sand",
"Bedrock",
"Basalt",
"Smooth Basalt",
"Glass",
"Loom",
"Cartography Table",
"Cauldron",
"Hay Bale",
"Cactus",
"Sugar Cane",
"Block Of Iron",
"Block Of Gold",
"Block Of Diamond",
"Block Of Emerald",
"Block Of Redstone",
"Block Of Amethyst",
"Budding Amethyst",
"Bookshelf",
"Azalea",
"Azalea Leaves",
"Big Dripleaf",
"Small Dripleaf",
"Deepslate",
"Chiseled Deepslate",
"Calcite",
"Cobbled Deepslate",
"Copper Block",
"Cut Copper",
"Cut Copper Stairs",
"Exposed Copper",
"Exposed Cut Copper",
"Weathered Copper Block",
"Weathered Cut Copper",
"Oxidized Copper Block",
"Oxidized Cut Copper",
"Deepslate Bricks",
"Deepslate Bricks Slab",
"Deepslate Bricks Stairs",
"Deepslate Redstone Ore",
"Deepslate Coal Ore",
"Deepslate Copper Ore",
"Deepslate Diamond Ore",
"Deepslate Emerald Ore",
"Deepslate Gold Ore",
"Deepslate Iron Ore",
"Deepslate Lapis Lazuli Ore",
"Deepslate Tiles",
"Deepslate Tile Stairs",
"Deepslate Tile Slab",
"Dripstone Block",
"Flowering Azalea",
"Flowering Azalea Leaves",
"Frogspawn",
"Glow Lichen",
"Glowing Item Frame",
"Hanging Roots",
"Jigsaw Block",
"Structure Block",
"Amethyst Cluster",
"Large Amethyst Bud",
"Medium Amethyst Bud",
"Small Amethyst Bud",
"Mangrove Door",
"Mangrove Leaves",
"Mangrove Log",
"Mangrove Planks",
"Mangrove Propagule",
"Mangrove Roots",
"Mangrove Trapdoor",
"Moss Block",
"Moss Carpet",
"Stripped Mangrove Log",
"Mud",
"Mudbrick",
"Muddy Mangrove Roots",
"Ochre Froglight",
"Pearlescent Froglight",
"Verdant Froglight",
"Packed Mud",
"Polished Deepslate",
"Block of Raw Copper",
"Block of Raw Gold",
"Block of Raw Iron",
"Reinforced Deepslate",
"Rooted Dirt",
"Sculk",
"Sculk Catalyst",
"Sculk Sensor",
"Sculk Shrieker",
"Tuff",
"Tinted Glass",
"Redstone Dust",
"Redstone Repeater",
"Stone Button",
"Oak Button",
"Redstone Lamp",
"Redstone Torch",
"Lever",
"Ender Pearl",
"Flint And Steel",
"Fire Charge",
"White Wool",
"Light Gray Wool",
"Gray Wool",
"Black Wool",
"Red Wool",
"Orange Wool",
"Yellow Wool",
"Lime Wool",
"Green Wool",
"Cyan Wool",
"Light Blue Wool",
"Blue Wool",
"Purple Wool",
"Magenta Wool",
"Pink Wool",
"Brown Wool",
"White Carpet",
"Light Gray Carpet",
"Gray Carpet",
"Black Carpet",
"Red Carpet",
"Orange Carpet",
"Yellow Carpet",
"Lime Carpet",
"Green Carpet",
"Cyan Carpet",
"Light Blue Carpet",
"Blue Carpet",
"Purple Carpet",
"Magenta Carpet",
"Pink Carpet",
"Brown Carpet",
"Stone Pressure Plate",
"Oak Pressure Plate",
"Chest",
}